//HintName: Warpstone.Sources.embedded.IParseInputSource.cs
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace Warpstone
{
    /// <summary>
    /// Interface for various input sources.
    /// </summary>
    public interface IParseInputSource
    {
    }
}

