//HintName: Warpstone.Sources.embedded.ParseOptions.cs
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace Warpstone
{
    /// <summary>
    /// Options to configure how the parsing should be done.
    /// </summary>
    public sealed record ParseOptions
    {
        /// <summary>
        /// The default <see cref="ParseOptions"/>.
        /// </summary>
        public static readonly ParseOptions Default = new();

        /// <summary>
        /// Determines the execution mode of the parser (default: <see cref="ParserExecutionMode.Auto"/>).
        /// </summary>
        public ParserExecutionMode ExecutionMode { get; init; } = ParserExecutionMode.Auto;

        /// <summary>
        /// Determines if left recursive grammars should automatically
        /// be transformed in a way to support left-recursion
        /// (default: <see langword="true"/>).
        /// </summary>
        public bool EnableAutomaticGrowingRecursion { get; init; } = true;

        /// <summary>
        /// Determines if grammars should automatically
        /// be transformed to support memoization
        /// (default: <see langword="false"/>).
        /// </summary>
        public bool EnableAutomaticMemoization { get; init; } = false;
    }
}

