//HintName: Warpstone.Sources.embedded.IRecursiveParseContext.cs
// <auto-generated/>
#pragma warning disable
#nullable enable annotations

namespace Warpstone
{
    /// <summary>
    /// Represents the context necessary for parsing recursively.
    /// </summary>
    public interface IRecursiveParseContext : IParseContext
    {
    }
}

